---
title: "Naxos - Exploratory Analyses"
author: "Kate Culhane"
date: "2/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}

# Load necessary packages

library(tidyverse)
library(vegan)

# Load necessary data

diet <- read_csv('./raw_data/diet_field.csv') %>% # diet data from field
  filter(island == 'Naxos')

inverts_meta <- read_csv('./raw_data/inverts_meta.csv') %>% # metadata for invert community field collection
  filter(island == 'Naxos')

pitfall <- read_csv('./raw_data/inverts_pitfall.csv') %>% # invert community data from pitfall traps
  filter(island == 'Naxos')

sticky <- read_csv('./raw_data/inverts_sticky.csv') %>% # invert community data from sticky traps
  filter(island == 'Naxos')

site_meta <- read_csv('./raw_data/site_meta.csv') # metadata for Naxos sites

site_veg <- read_csv('./raw_data/site_veg.csv') # vegetation quadrat data for Naxos sites

```

### ANALYSES TO DO

1. NMDS for prey communities
2. NMDS for lizard diet
3. Adonis between site types